### ISSUE TITLE
I want to know about your LISCENSE

### ISSUE THREAD

**Issue by ghost** [searchivarius/EphyraQuestionAnalysis#1]
hello, thanks for good project. Is their any LISCENSE in this project?

**Comment by searchivarius** [comment]
Hi except 3rd party code it is Apache 2.

**Comment by searchivarius** [comment]
ohh sorry I thought you were asking about nmslib. for Ephyra you need to
check the original Open Ephyra license.

**Comment by searchivarius** [comment]
see the update

**Comment by ghost** [comment]
Thank you!
